<?php
namespace cassandra;
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/Thrift.php';


$GLOBALS['\cassandra\E_ConsistencyLevel'] = array(
  'ONE' => 1,
  'QUORUM' => 2,
  'LOCAL_QUORUM' => 3,
  'EACH_QUORUM' => 4,
  'ALL' => 5,
  'ANY' => 6,
  'TWO' => 7,
  'THREE' => 8,
);

final class ConsistencyLevel {
  const ONE = 1;
  const QUORUM = 2;
  const LOCAL_QUORUM = 3;
  const EACH_QUORUM = 4;
  const ALL = 5;
  const ANY = 6;
  const TWO = 7;
  const THREE = 8;
  static public $__names = array(
    1 => 'ONE',
    2 => 'QUORUM',
    3 => 'LOCAL_QUORUM',
    4 => 'EACH_QUORUM',
    5 => 'ALL',
    6 => 'ANY',
    7 => 'TWO',
    8 => 'THREE',
  );
}

$GLOBALS['\cassandra\E_IndexOperator'] = array(
  'EQ' => 0,
  'GTE' => 1,
  'GT' => 2,
  'LTE' => 3,
  'LT' => 4,
);

final class IndexOperator {
  const EQ = 0;
  const GTE = 1;
  const GT = 2;
  const LTE = 3;
  const LT = 4;
  static public $__names = array(
    0 => 'EQ',
    1 => 'GTE',
    2 => 'GT',
    3 => 'LTE',
    4 => 'LT',
  );
}

$GLOBALS['\cassandra\E_IndexType'] = array(
  'KEYS' => 0,
  'CUSTOM' => 1,
);

final class IndexType {
  const KEYS = 0;
  const CUSTOM = 1;
  static public $__names = array(
    0 => 'KEYS',
    1 => 'CUSTOM',
  );
}

$GLOBALS['\cassandra\E_Compression'] = array(
  'GZIP' => 1,
  'NONE' => 2,
);

final class Compression {
  const GZIP = 1;
  const NONE = 2;
  static public $__names = array(
    1 => 'GZIP',
    2 => 'NONE',
  );
}

$GLOBALS['\cassandra\E_CqlResultType'] = array(
  'ROWS' => 1,
  'VOID' => 2,
  'INT' => 3,
);

final class CqlResultType {
  const ROWS = 1;
  const VOID = 2;
  const INT = 3;
  static public $__names = array(
    1 => 'ROWS',
    2 => 'VOID',
    3 => 'INT',
  );
}

$GLOBALS['THRIFT_AUTOLOAD']['cassandra\column'] = 'cassandra/cassandra.Column.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\supercolumn'] = 'cassandra/cassandra.SuperColumn.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\countercolumn'] = 'cassandra/cassandra.CounterColumn.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\countersupercolumn'] = 'cassandra/cassandra.CounterSuperColumn.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\columnorsupercolumn'] = 'cassandra/cassandra.ColumnOrSuperColumn.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\notfoundexception'] = 'cassandra/cassandra.NotFoundException.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\invalidrequestexception'] = 'cassandra/cassandra.InvalidRequestException.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\unavailableexception'] = 'cassandra/cassandra.UnavailableException.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\timedoutexception'] = 'cassandra/cassandra.TimedOutException.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\authenticationexception'] = 'cassandra/cassandra.AuthenticationException.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\authorizationexception'] = 'cassandra/cassandra.AuthorizationException.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\schemadisagreementexception'] = 'cassandra/cassandra.SchemaDisagreementException.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\columnparent'] = 'cassandra/cassandra.ColumnParent.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\columnpath'] = 'cassandra/cassandra.ColumnPath.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\slicerange'] = 'cassandra/cassandra.SliceRange.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\slicepredicate'] = 'cassandra/cassandra.SlicePredicate.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\indexexpression'] = 'cassandra/cassandra.IndexExpression.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\indexclause'] = 'cassandra/cassandra.IndexClause.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\keyrange'] = 'cassandra/cassandra.KeyRange.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\keyslice'] = 'cassandra/cassandra.KeySlice.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\keycount'] = 'cassandra/cassandra.KeyCount.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\deletion'] = 'cassandra/cassandra.Deletion.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\mutation'] = 'cassandra/cassandra.Mutation.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\endpointdetails'] = 'cassandra/cassandra.EndpointDetails.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\tokenrange'] = 'cassandra/cassandra.TokenRange.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\authenticationrequest'] = 'cassandra/cassandra.AuthenticationRequest.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\columndef'] = 'cassandra/cassandra.ColumnDef.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cfdef'] = 'cassandra/cassandra.CfDef.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\ksdef'] = 'cassandra/cassandra.KsDef.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cqlrow'] = 'cassandra/cassandra.CqlRow.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cqlmetadata'] = 'cassandra/cassandra.CqlMetadata.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cqlresult'] = 'cassandra/cassandra.CqlResult.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cqlpreparedresult'] = 'cassandra/cassandra.CqlPreparedResult.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_login_args'] = 'cassandra/cassandra.Cassandra_login_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_login_result'] = 'cassandra/cassandra.Cassandra_login_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_set_keyspace_args'] = 'cassandra/cassandra.Cassandra_set_keyspace_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_set_keyspace_result'] = 'cassandra/cassandra.Cassandra_set_keyspace_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_args'] = 'cassandra/cassandra.Cassandra_get_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_result'] = 'cassandra/cassandra.Cassandra_get_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_slice_args'] = 'cassandra/cassandra.Cassandra_get_slice_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_slice_result'] = 'cassandra/cassandra.Cassandra_get_slice_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_count_args'] = 'cassandra/cassandra.Cassandra_get_count_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_count_result'] = 'cassandra/cassandra.Cassandra_get_count_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_multiget_slice_args'] = 'cassandra/cassandra.Cassandra_multiget_slice_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_multiget_slice_result'] = 'cassandra/cassandra.Cassandra_multiget_slice_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_multiget_count_args'] = 'cassandra/cassandra.Cassandra_multiget_count_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_multiget_count_result'] = 'cassandra/cassandra.Cassandra_multiget_count_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_range_slices_args'] = 'cassandra/cassandra.Cassandra_get_range_slices_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_range_slices_result'] = 'cassandra/cassandra.Cassandra_get_range_slices_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_paged_slice_args'] = 'cassandra/cassandra.Cassandra_get_paged_slice_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_paged_slice_result'] = 'cassandra/cassandra.Cassandra_get_paged_slice_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_indexed_slices_args'] = 'cassandra/cassandra.Cassandra_get_indexed_slices_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_get_indexed_slices_result'] = 'cassandra/cassandra.Cassandra_get_indexed_slices_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_insert_args'] = 'cassandra/cassandra.Cassandra_insert_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_insert_result'] = 'cassandra/cassandra.Cassandra_insert_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_add_args'] = 'cassandra/cassandra.Cassandra_add_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_add_result'] = 'cassandra/cassandra.Cassandra_add_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_remove_args'] = 'cassandra/cassandra.Cassandra_remove_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_remove_result'] = 'cassandra/cassandra.Cassandra_remove_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_remove_counter_args'] = 'cassandra/cassandra.Cassandra_remove_counter_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_remove_counter_result'] = 'cassandra/cassandra.Cassandra_remove_counter_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_batch_mutate_args'] = 'cassandra/cassandra.Cassandra_batch_mutate_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_batch_mutate_result'] = 'cassandra/cassandra.Cassandra_batch_mutate_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_truncate_args'] = 'cassandra/cassandra.Cassandra_truncate_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_truncate_result'] = 'cassandra/cassandra.Cassandra_truncate_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_schema_versions_args'] = 'cassandra/cassandra.Cassandra_describe_schema_versions_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_schema_versions_result'] = 'cassandra/cassandra.Cassandra_describe_schema_versions_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_keyspaces_args'] = 'cassandra/cassandra.Cassandra_describe_keyspaces_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_keyspaces_result'] = 'cassandra/cassandra.Cassandra_describe_keyspaces_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_cluster_name_args'] = 'cassandra/cassandra.Cassandra_describe_cluster_name_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_cluster_name_result'] = 'cassandra/cassandra.Cassandra_describe_cluster_name_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_version_args'] = 'cassandra/cassandra.Cassandra_describe_version_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_version_result'] = 'cassandra/cassandra.Cassandra_describe_version_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_ring_args'] = 'cassandra/cassandra.Cassandra_describe_ring_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_ring_result'] = 'cassandra/cassandra.Cassandra_describe_ring_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_partitioner_args'] = 'cassandra/cassandra.Cassandra_describe_partitioner_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_partitioner_result'] = 'cassandra/cassandra.Cassandra_describe_partitioner_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_snitch_args'] = 'cassandra/cassandra.Cassandra_describe_snitch_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_snitch_result'] = 'cassandra/cassandra.Cassandra_describe_snitch_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_keyspace_args'] = 'cassandra/cassandra.Cassandra_describe_keyspace_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_keyspace_result'] = 'cassandra/cassandra.Cassandra_describe_keyspace_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_splits_args'] = 'cassandra/cassandra.Cassandra_describe_splits_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_describe_splits_result'] = 'cassandra/cassandra.Cassandra_describe_splits_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_add_column_family_args'] = 'cassandra/cassandra.Cassandra_system_add_column_family_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_add_column_family_result'] = 'cassandra/cassandra.Cassandra_system_add_column_family_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_drop_column_family_args'] = 'cassandra/cassandra.Cassandra_system_drop_column_family_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_drop_column_family_result'] = 'cassandra/cassandra.Cassandra_system_drop_column_family_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_add_keyspace_args'] = 'cassandra/cassandra.Cassandra_system_add_keyspace_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_add_keyspace_result'] = 'cassandra/cassandra.Cassandra_system_add_keyspace_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_drop_keyspace_args'] = 'cassandra/cassandra.Cassandra_system_drop_keyspace_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_drop_keyspace_result'] = 'cassandra/cassandra.Cassandra_system_drop_keyspace_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_update_keyspace_args'] = 'cassandra/cassandra.Cassandra_system_update_keyspace_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_update_keyspace_result'] = 'cassandra/cassandra.Cassandra_system_update_keyspace_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_update_column_family_args'] = 'cassandra/cassandra.Cassandra_system_update_column_family_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_system_update_column_family_result'] = 'cassandra/cassandra.Cassandra_system_update_column_family_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_execute_cql_query_args'] = 'cassandra/cassandra.Cassandra_execute_cql_query_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_execute_cql_query_result'] = 'cassandra/cassandra.Cassandra_execute_cql_query_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_prepare_cql_query_args'] = 'cassandra/cassandra.Cassandra_prepare_cql_query_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_prepare_cql_query_result'] = 'cassandra/cassandra.Cassandra_prepare_cql_query_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_execute_prepared_cql_query_args'] = 'cassandra/cassandra.Cassandra_execute_prepared_cql_query_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_execute_prepared_cql_query_result'] = 'cassandra/cassandra.Cassandra_execute_prepared_cql_query_result.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_set_cql_version_args'] = 'cassandra/cassandra.Cassandra_set_cql_version_args.php';
$GLOBALS['THRIFT_AUTOLOAD']['cassandra\cassandra_set_cql_version_result'] = 'cassandra/cassandra.Cassandra_set_cql_version_result.php';
?>
