<?php
namespace cassandra;
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/cassandra/cassandra_types.php';

$GLOBALS['cassandra_cassandra_CONSTANTS'] = array();

$GLOBALS['cassandra_cassandra_CONSTANTS']['VERSION'] = "19.30.0";

?>
